### ISSUE TITLE
No module named "requests"

### ISSUE THREAD

**Issue by DyeffersonAz** [kokosxD/find-lyrics#2]
Your program doesn't open. Look at the error:
```
Traceback (most recent call last):
  File "C:\Users\USURIO~2\AppData\Local\Temp\find-lyrics-master\find_lyrics.py", line 1, in <module>
    import requests as rq
ModuleNotFoundError: No module named 'requests'
```

**Comment by ubtofficial** [comment]
This is a python script, not a virtual environment. You are running it like a script you wrote in an IDE. Therefor you should install the requests method. You can do that like pip install requests

**Comment by kokosxD** [comment]
i have run successfully my program multiple times and it worked without eny errors.

**Comment by anselal** [comment]
You have some dependencies installed. I have open a pull request to include a requirements.txt file
